# Generated by Django 3.0.4 on 2020-04-06 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200406_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformmessage',
            name='status',
            field=models.CharField(choices=[('True', 'Evet'), ('Read', 'Read')], default='New', max_length=10),
        ),
    ]
